#!/bin/sh

# Run the script and get the return code if successful of if fails
if ! grep -qE ^"feat|fix" "$1";then
    cat "$MSG"
    echo "Commit message must begin with the words 'feat' or 'fix'"
    exit 1
fi