name: Build

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Tags
        run: git fetch --prune --unshallow --tags

      - name: Generate debug build
          env:
            VERSION_CODE: ${{ github.run_number}}
          run: ./gradlew clean assembleDebug

          - name: Upload debug build
            uses: actions/upload-artifact@master
            with:
              name: Brownbag-debug.apk
              path: app/build/outputs/apk/debug/*.apk

      - name: Generate release build
        env:
          VERSION_CODE: ${{ github.run_number}}
        run: ./gradlew clean assembleRelease

      - name: Sign release build
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ALIAS_PASSWORD }}

      - name: Upload release build
        uses: actions/upload-artifact@master
        with:
          name: Brownbag-release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Upload release mapping file
        uses: actions/upload-artifact@master
        with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt