name: Lint Checks

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Fetch rlease tags
        run: git fetch --prune --unshallow --tags

      - name: Generate lint reports
        run: ./gradlew lintDebug

      - name: Upload lint reports
        uses: actions/upload-artifact@master
        with:
          name: android-lint-reports
          path: build/reports/*.html